import "@/assets/css/bootstrap.min.css";
import "@/assets/css/dashboard-style.css";




import Header from './components/Header';
import Sidebar from './components/Sidebar';
import Footer from './components/Footer';

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="dashboard logged-in">
                <div className="dashboard-wrap">
                    <Sidebar/>
                    <div className="right">
                        <Header/>
                        <div className="content">
                            {children}
                        </div>
                        <Footer/>
                    </div>
                </div>
            </body>
        </html>
    );
}